name: Deploy Telegram Bot

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Setup SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ secrets.SERVER_URL }} >> ~/.ssh/known_hosts

      - name: Deploy Bot
        run: |
          ssh -i ~/.ssh/id_ed25519 root@${{ secrets.SERVER_URL }} << 'EOF'
            cd /root/coffee-bot
            git pull origin master
            npm install
            pm2 restart coffee-bot
          EOF
